# Generated by Django 3.2 on 2021-04-23 22:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_remove_survey_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='id',
            field=models.UUIDField(
                default=uuid.uuid5, editable=False, primary_key=True, serialize=False),
        ),
    ]
