# Generated by Django 3.2 on 2021-04-25 00:02

import surveys.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_alter_survey_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='image',
            field=models.ImageField(
                null=True, upload_to=surveys.models.survey_upload_file_path),
        ),
    ]
